name: Laravel Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Change according to your PHP version

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up Laravel environment
      run: cp .env.example .env && php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit
